name: Repo Generator

on:
   workflow_dispatch:
      inputs:
         Generate_Table_Of_Contents:
            description: 'Generate Table Of Contents'
            type: boolean
            required: false
         Replace_Links_In_Markdown:
            description: 'Update all links'
            type: boolean
            required: false
         Update_Code_Of_Conduct_EMAIL:
            description: 'Update Code Of Conduct email'
            type: boolean
            required: false
         Update_Security_Policy_EMAIL:
            description: 'Update Security Policy email'
            type: boolean
            required: false
         Compress_Images:
            description: 'Compress / Optimize images'
            type: boolean
            required: false        
         Generate_Index_File:
            description: 'Generate Index file'
            type: boolean
            required: false
         Download_Files_Or_Folder:
            description: 'Download a file or folder from a GitHub Repo'
            required: False
            default: ''

permissions:
  contents: write

jobs:
  Repo_Builder:
    name: Repo Template Builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generating Table Of Contents
        if: ${{  github.event.inputs.Generate_Table_Of_Contents == 'true' }}
        run: |
          npx markdown-toc-gen update README.md 

      - name: Updating links in README content
        if: ${{  github.event.inputs.Replace_Links_In_Markdown == 'true' }}
        run: |
          sudo apt-get install python3
          python3 .github/scripts/replace_repo_links.py

      - name: Updating Code Of Conduct E-Mail
        if: ${{  github.event.inputs.Update_Code_Of_Conduct_EMAIL == 'true' }}
        run: |
          sudo apt-get install python3
          python3 .github/scripts/replace_code_of_conduct_info.py
 
      - name: Updating Security Policy E-Mail
        if: ${{  github.event.inputs.Update_Security_Policy_EMAIL == 'true' }}
        run: |
          sudo apt-get install python3
          python3 .github/scripts/replace_security_policy_email.py

      - name: Optimizing Images
        if: ${{  github.event.inputs.Compress_Images == 'true' }}
        run: |
          sudo apt-get install python3 python3-pip
          pip3 install pillow optimize-images
          optimize-images ./          

      - name: Generating Index File
        if: ${{  github.event.inputs.Generate_Index_File == 'true' }}
        run: |
          sudo apt-get install python3 
          INPUT_STORE=${{ github.event.repository.url }} python3 .github/scripts/generate_index_file.py

      - name: Downloading file / folder from GitHub Repo
        if: ${{  github.event.inputs.Download_Files_Or_Folder != ''}}
        run: |
          chmod +x .github/scripts/shell/github_downloader.sh
          .github/scripts/shell/github_downloader.sh ${{  github.event.inputs.Download_Files_Or_Folder}} 

      - name: Commiting updates
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Updated Content"
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF_NAME}
